### ISSUE TITLE
Missing template/default/zookeeper.initd.erb file?

### ISSUE THREAD

**Issue by fhwang** [evertrue/zookeeper-cookbook#138]
bb9e15 refers to a `zookeeper.initd.erb` template, but it wasn't part of that commit and can't be found anywhere in the project. Was it left out of the commit by accident?

**Comment by fhwang** [comment]
Oops, here's the SHA: bb9e156031feec452f37d1fef74e396732973ca4

**Comment by jeffbyrnes** [comment]
Hmm, yeah, #136 does seem to be missing an actual SysV script. However, you could supply your own in your wrapper cookbook, so that’s an option.

Still, we should have one here.

**Comment by fhwang** [comment]
Cool, no problem. We're probably fine on our end, just thought you guys might like to know in case it was unintentional.

**Comment by jeffbyrnes** [comment]
This was fixed in #148 & shipped in v2.13.0.
