### ISSUE TITLE
Apache mirror is unavailable

### ISSUE THREAD

**Issue by pupska** [evertrue/zookeeper-cookbook#170]
Hi,

looks like this source no more longer awailable:

default[:zookeeper][:mirror]      = 'http://www.poolsaboveground.com/apache/zookeeper'

**Comment by neil-greenwood** [comment]
It's probably a version number problem. I can browse to that link.

**Comment by jeffbyrnes** [comment]
Last time this happened, it was b/c ZK had released a new version (3.4.6) & the old one was removed (3.4.5). No idea why they did it that way.

**Comment by jeffbyrnes** [comment]
Looks like that’s the case, 3.4.6 and 3.4.8 are available at that URL, but not 3.4.5, which this cookbook expects.

@pupska please just specify a newer ZK version in your wrapper cookbook to get around this for now.

**Comment by pupska** [comment]
thanks @jeffbyrnes.

**Comment by popsikle** [comment]
This is failing again.

```
           * remote_file[zookeeper-3.4.8] action create[2016-06-03T17:07:21+00:00] WARN: remote_file[zookeeper-3.4.8] cannot be downloaded from http://www.poolsaboveground.com/apache/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz: 404 "Not Found"


             ================================================================================
             Error executing action `create` on resource 'remote_file[zookeeper-3.4.8]'
             ================================================================================

             Net::HTTPServerException
             ------------------------
             404 "Not Found"

```

Setting mirror to 'http://apache.mirrors.tds.net/zookeeper/' resolved the issue for me.

**Comment by jeffbyrnes** [comment]
Thanks @popsikle. I’ll see about cutting a new version with that URL.
