### ISSUE TITLE
Question about your pinning strategy

### ISSUE THREAD

**Issue by kisoku** [evertrue/zookeeper-cookbook#181]
Looking at the pins you just set, it seems like you are pinning to cookbooks to maintain Chef 11 support.

You've pinned build-essential to a really ancient version of build-essential (2.2). The last version of build-essential that supports Chef 11 is 3.2. Is your pin intentional ? I can't see what makes 2.2 special and this it really difficult to use this cookbook without forking it.

**Comment by jeffbyrnes** [comment]
@kisoku great question. My teammate & I have been going back & forth on these, and we’ve decided relaxing them is the better option, with a minimum known-good verison.

I’ll clean this up soon.

**Comment by jeffbyrnes** [comment]
@kisoku fixed in v6.0.0
