### ISSUE TITLE
cookbook dependancies in the metadata

### ISSUE THREAD

**Issue by Stromweld** [evertrue/zookeeper-cookbook#187]
cookbook dependencies should specify minimum version instead of approximate version(>= instead of ~>). This allows dependencies to be upgraded to latest version, with bug fixes and enhancements, even if major version changes without update of this cookbook. If breaking change is found then pinning to specifc version makes more sense and should be noted in changelog and or readme.

**Comment by Stromweld** [comment]
@eherot can this get pushed to the supermarket?

**Comment by jeffbyrnes** [comment]
@Stromweld I can cut a new version, stand by…

**Comment by jeffbyrnes** [comment]
@Stromweld all set! v8.0.0 has been published to Supermarket.

**Comment by Stromweld** [comment]
sweet thanks
