### ISSUE TITLE
Support "package" install style

### ISSUE THREAD

**Issue by eherot** [evertrue/zookeeper-cookbook#192]

**Comment by jeffbyrnes** [comment]
This one is really tough, b/c the package installer tends to do a few things:

1. get in the way of config mgmt.
2. try to manage the ZK service itself

Still, worth trying out at some point!

**Comment by eherot** [comment]
Indeed, but neither of those things are particularly unique to the ZK package.

**Comment by jeffbyrnes** [comment]
@eherot true, though in the case of ZK, restarting the service is dicey. Still, we handled that w/ Elasticsearch and Cassandra, so it’s all good.

**Comment by jeffbyrnes** [comment]
Closing this, as it is unlikely to happen.
