### ISSUE TITLE
Any feedback with ZK 3.5.2 dynamic configuration ?

### ISSUE THREAD

**Issue by scalp42** [evertrue/zookeeper-cookbook#198]
Curious if folks had luck using this cookbook with ZooKeeper 3.5.2 for example, including the dynamic configuration aspect: https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html

**Comment by jeffbyrnes** [comment]
I’m not using ZooKeeper at my current job, so nope! I know @eherot is still using it for a bunch of things, however, so perhaps he has insight.

**Comment by eherot** [comment]
There's a branch for this which I have made into a PR: #199 I don't remember exactly what state I left it in but I think it's _mostly_ working.

**Comment by jeffbyrnes** [comment]
Solved with v13.0.0
