### ISSUE TITLE
How to run ZooKeeper as a service

### ISSUE THREAD

**Issue by ashu-3** [evertrue/zookeeper-cookbook#202]
Hi Everyone
I am new to zookeeper as well as for Linux. I installed and run zookeeper as a cluster in 3 machines. Now I want to run ZooKeeper as a service and I tried following command.

apt-get install zookeeperd
and then
service zookeeper start

but I am getting error that says Failed to start zookeeper, unit zookeeper.service not found..

Processing triggers for ca-certificates (20160104ubuntu1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Errors were encountered while processing:
/var/cache/apt/archives/zookeeperd_3.4.8-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@deds14:# service zookeeper status
● zookeeper.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)
root@deds14:# service zookeeper start
Failed to start zookeeper.service: Unit zookeeper.service not found.

Any help will be appreciated

**Comment by jeffbyrnes** [comment]
@ashu-3 this isn’t a forum for support for ZooKeeper itself. This project is a Chef cookbook to install, configure, and run ZooKeeper.

You’ll want to check out the [official ZooKeeper website](https://zookeeper.apache.org) for some resources. Best of luck!
