### ISSUE TITLE
support direct link to tar for download path

### ISSUE THREAD

**Issue by gregorskii** [evertrue/zookeeper-cookbook#204]
The cookbooks LWRP passes in the mirror and builds the tar path itself. Can this cookbook support direct links to a self-hosted copy of the tar, say in S3?

Thanks

**Comment by jeffbyrnes** [comment]
It could! Pull requests are welcome 😄

**Comment by jeffbyrnes** [comment]
This can already work this way, the download url for the `ark` resources that grabs & unpacks the archive looks like this:

```ruby
"#{new_resource.mirror}/zookeeper-#{new_resource.version}/zookeeper-#{new_resource.version}.tar.gz"
```

So you simply need to structure the URL to your self-hosted copy such that the file is named `zookeeper-#{version}/zookeeper-#{version}.tar.gz`, and set the `mirror` value to whatever precedes that.

Closing this out.
