### ISSUE TITLE
MYID

### ISSUE THREAD

**Issue by joshskains** [evertrue/zookeeper-cookbook#213]
Am I missing something or am I required to write into a wrapper cookbook a method of populating the MYID on all the servers?

**Comment by jeffbyrnes** [comment]
@joshskains that would be something your wrapper should do. This cookbook makes no attempts to write the `MYID` anywhere. Partly, that owes to it originally being tightly coupled to the `exhibitor` cookbook, which handles that for you (amongst other things).

Of course, not everyone wants to use Exhibitor to manage their cluster, but method for managing IDs differ, so we never included this functionality.

**Comment by jeffbyrnes** [comment]
Pull requests are welcome, as I have very limited time to work on this cookbook.

**Comment by joshskains** [comment]
Ok. Thanks. I wanted to make sure I wasn't doing redundant work and was going to suggest more documentation on clustering. I'm not good at making highly flexible patterns, so any contribution I would have would be limited by that. IE: my wrapper that is feeding in data has three attributes for the three servers I am patterning all our clusters on. I have not learned ruby enough to make it flexible for alternate patterns (IE: a hash). I'm a perl person, so I'd have a while() or a for statement going through the hash. :)

**Comment by jeffbyrnes** [comment]
No worries, @joshskains. Perhaps someone else will come along & add the functionality, but that should work for you!
