### ISSUE TITLE
Default install fails with failure to download Zookeeper 3.4.12

### ISSUE THREAD

**Issue by cbaenziger** [evertrue/zookeeper-cookbook#218]
[Zookeeper](https://zookeeper.apache.org/releases.html) released 3.4.14 and the link for 3.4.12 is now gone. As such to converge successfully, one needs to override:
* `node['zookeeper']['version']` to be `3.4.14`
* `node['zookeeper']['checksum']` to be [`b14f7a0fece8bd34c7fffa46039e563ac5367607c612517aa7bd37306afbd1cd`](https://apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz.sha256)

**Comment by jeffbyrnes** [comment]
@cbaenziger thanks for the heads-up. I’m a bit time-constrained, and not using the cookbook regularly at the moment; would you be willing to write a PR that updates the default values in this cookbook?

Thanks to how Apache handles versions, and that restarting ZooKeeper can mean potential data loss, this will be a major version for this cookbook.

**Comment by jeffbyrnes** [comment]
@cbaenziger I got some time, finally, and with @hrak’s help, this was closed in #219, and released as v12.0.0.
