### ISSUE TITLE
Inconsistency in username properties across resources

### ISSUE THREAD

**Issue by hrak** [evertrue/zookeeper-cookbook#226]
There is an inconsistency in the username properties for the resources. For the `zookeeper` and `zookeeper_service` resources the property is `username`, while for the `zookeeper_config` resources it is `user`.

**Comment by jeffbyrnes** [comment]
Good point.

I’ve been thinking of collapsing these into a single resource; any thoughts on that?

**Comment by jeffbyrnes** [comment]
Regardless of whether they are collapsed together, or not, this will be a breaking change. I’m working on dropping Chef 14 support anyway in #225, so I’ll handle this then, too.
