### ISSUE TITLE
Implement zookeeper_service

### ISSUE THREAD

**Issue by jakedavis** [evertrue/zookeeper-cookbook#86]
The Zookeeper docs [recommend](http://zookeeper.apache.org/doc/trunk/zookeeperAdmin.html#sc_supervision) process supervision. As a baseline, we should have a resource which basically calls `zkServer.sh start`. But as a more resilient solution, we should probably have a Runit option, and possibly others depending on peoples' cup of tea.

**Comment by corbesero** [comment]
Is there some way to control what user zookeeper is run as using runit?  If I use systemv, zookeeper runs as zookeeper.  But with runit, it always seems to start up as root.

**Comment by jeffbyrnes** [comment]
@corbesero that’d be a separate issue, which I’ve opened here: #166. This issue is meant to cover a refactor of how the service is set up; it should be refactored as its own custom resource.

**Comment by jeffbyrnes** [comment]
I think this would best be served as part of a larger refactor of the LWRPs into Chef 12.5-style custom resources.
